### PR TITLE
Added restriction for user to vote max three times per post

### PR DESCRIPTION
**Pull request by jankowiakmaria**
Because it's annoying to see 20 votes from one person...

### CODE REVIEW

**Comment by seif** [comment]
We allow multiple votes in badgers retros. Each engineer gets 3 votes, and they can use all of them on a post if they like.

**Comment by jankowiakmaria** [comment]
I see. I updated to limit to three (short term solution), but would be good to have it configurable at the board level.

**Comment by seif** [comment]
@jankowiakmaria yeah, Ideally all the on this fork would be configurable and pushed upstream to the main repo...

**Comment by seif** [comment]
thanks btw

**Comment by jankowiakmaria** [comment]
@seif agree. I need to understand redux and stuff to do that 😄

**Pull request merged**
